exports.EErrors = {
    ROUTING_ERROR: 1,
    INVALID_TYPE_ERROR: 2,
    DATABASE_ERROR: 3,
    SERVER_ERROR: 4,
    AUTHENTICATION_ERROR: 5, 
    AUTHORIZATION_ERROR: 6,
    INVALID_OPERATION_ERROR: 7,
    EXTERNAL_API_ERROR: 8,
    MISSING_PARAMETER_ERROR: 9,
    UNEXPECTED_ERROR: 10
}